--
--
-- MySQL tables used to run the Editor examples.
--
-- For more information about how the client and server-sides interact, please
-- refer to the Editor documentation: http://editor.datatables.net/manual .
--
--


--
-- To do list examples
--
DROP TABLE IF EXISTS yacback;

CREATE TABLE `yacback` (
    `id` int(10) NOT NULL auto_increment,
    `rn` float,
    `tag` varchar(10) NOT NULL default '',
    `en` varchar(100) NOT NULL default '',
    `es` varchar(100) NOT NULL default '',
    `me` varchar(100) NOT NULL default '',
    PRIMARY KEY (`id`)
);

INSERT INTO `yacback` (`tag`, `en`, `es`, `me`)
    VALUES
( '4k', 'you donZZZt forget how',       'no se olvida', ''),
( '3c', 'she handed me',        'me entregó', ''),
( '4e', 'almost invisible',     'casi invisible', ''),
( '3a', 'that if I valued my life at all',      'si en algo valoraba mi existencia', ''),
( '4l', 'IZZZm trying to go in chronological order',    'trato de avanzar en orden cronológico', ''),
( '4e', 'IZZZm on a island',    'estoy en un islote', ''),
( '3n', 'to communicate with the dead', 'para comunicarse con los muertos', ''),
( '4j', 'writing is like riding a bicycle',     'escribir es como andar un bicicleta', ''),
( '4m', 'I go off on tangents', 'me voy por las ramas', ''),
( '3o', 'but itZZZs true that', 'pero es cierto que', ''),
( '4h', 'I am writing by hand', 'estoy escribiendo a mano', ''),
( '3f', 'the monumental stupidities',   'las tonterías monumentales', ''),
( '4g', 'but I intend to correct this defect',  'pero he propuesto corregir ése defecto', ''),
( '3b', 'in my case',   'en mi caso', ''),
( '4g', 'can be tedious',       'puede ser tediosa', ''),
( '3h', 'under lock and key',   'bajo llave', ''),
( '3i', 'under her bed',        'debajo su cama', ''),
( '4h', 'and thatZZZs why now', 'y asi es como ahora', ''),
( '3f', 'to write down',        'para escribir', ''),
( '3m', 'professionals who charge',     'profesionales que ganan', ''),
( '4f', 'how much I actually remember', 'cuánto recuerdo', ''),
( '3l', 'a huge pile of tales', 'un montón de fábulas', ''),
( '4g', 'in the future',        'en el futuro', ''),
( '3h', 'industrial-strength adhesive tape',    'cinta adhesiva industrial', ''),
( '3h', 'several of my diaries are still in existence', 'existen varios diarios mios', ''),
( '3m', 'are not profitable for them',  'no les convienen', ''),
( '4g', 'the bare truth',       'la estricta verdad', ''),
( '3a', 'a week ago',   'hace una semana', ''),
( '3k', 'when I get psychoanalyzed',    'cuanda me haga un psicoanálisis', ''),
( '3i', 'in a shoebox', 'en una caja de zapatos', ''),
( '4d', 'has been a long one for me',   'ha sido larga para mí', ''),
( '3o', 'in my backpack',       'en mi mochila', ''),
( '3a', 'I should not get in touch with anyone I knew', 'no me comunicara con nadie conocido', ''),
( '3a', 'at the airport',       'en el aeropuerto', ''),
( '3d', 'from the age of eight',        'desde los ochos años', ''),
( '4i', 'it will gradually straighten out',     'se irá enderezando', ''),
( '4l', 'since some sort of order is required', 'ya algun orden se requiere', ''),
( '3h', 'my grandfather kept them',     'mi abuelo guardaba', ''),
( '3a', 'my enemies',   'mis enemigos', ''),
( '3b', 'she wasn´t exaggerating',      'no exageraba', ''),
( '4h', 'when even they use computers', 'cuando ? ellos usan computadoras', ''),
( '3k', 'of my personality',    'de mi personalidad', ''),
( '4g', 'I change or exaggerate it',    'la cambio o la exagero', ''),
( '3f', 'take advantage of it', 'aprovecha', ''),
( '4f', 'and how much is a product of my imagination',  'y cuánto es un producto de mi imaginación', ''),
( '3j', 'this will be', 'ese sería', ''),
( '3g', 'to see if',    'a ver si', ''),
( '4k', 'without doing it',     'sin practicar', ''),
( '4i', 'but I imagine',        'pero supongo', ''),
( '3l', 'but if she read them', 'pero si hubiera leído', ''),
( '3e', 'to get bored', 'de aburrirte', ''),
( '3o', 'and writing is one way',       'y escribir es una forma de', ''),
( '3e', 'you´re going to have time',    'vas a tener tiempo', ''),
( '3l', 'Freud himself',        'al mismo Freud', ''),
( '3o', 'with no intention of using it',        'sin intención de usarlo', ''),
( '3m', 'by the hour',  'por hora', ''),
( '3j', 'notebook number nine', 'cuaderno número 9', ''),
( '4f', 'to write about my life',       'escribir sobre mi vida', ''),
( '3m', 'since quick results',  'ya que los resultados rápidos', ''),
( '3k', 'mi Nini thinks',       'mi Nini cree que', ''),
( '3c', 'so I could keep a diary',      'para llevara un diario de vida', ''),
( '3n', 'and from the traps of magic',  'y de las trampas de la magia', ''),
( '3m', 'on principle', 'en el principio', ''),
( '3h', 'in his desk',  'en su escritorio', ''),
( '3d', 'as I did',     'como hice', ''),
( '3g', 'you can come to grips with them',      'les tomas el peso', ''),
( '4g', 'and so',       'y asi ?', ''),
( '3c', 'a hundred-page notebook',      'un cuaderno de cien hojas', ''),
( '3a', 'my grandmother gave me a dry-eyed hug',        'mi abuela me abrazó sin lágrimas', ''),
( '4m', 'but I lose my thread', 'pero pierdo el hilo', ''),
( '4m', 'or I remember something important',    'o acuerdo de algun importante', ''),
( '4g', 'and lie as little as possible',        'y mentir lo menos posible', ''),
( '3n', 'however she makes an exception',       'sin embargo hace una excepción', ''),
( '4i', 'page by page', 'página a página', ''),
( '4f', 'because I donZZZt know',       'porque no sé', ''),
( '3n', 'for psychiatrists',    'con los psichiátras', ''),
( '3m', 'my grandmother distrusts',     'mi abuela desconfia de', ''),
( '3o', 'so I wouldn´t upset her',      'para no ofendarla', ''),
( '3n', 'when she took it into her head',       'cuando le dio', ''),
( '3h', 'sealed with',  'sellados con', ''),
( '3f', 'you´ve committed',     'has cometido', ''),
( '4i', 'and my writing must be in Cyrillic script',    'y mi escritura debe de ser cirílica', ''),
( '4i', 'because I canZZZt even decipher it myself',    'ya que yo mismo no discifrala', ''),
( '3o', 'I put the notebook',   'puse el cuaderno', ''),
( '3k', 'they will be of use to me',    'me sirvirán', ''),
( '3l', 'capable of misleading',        'capaces de despistar', ''),
( '4d', 'this first week of exile',     'esta primera semana de exilio', ''),
( '3a', 'she told me again',    'me repitió', ''),
( '4l', 'that would make it easy',      'esa ser ? facil', ''),
( '3i', 'now my Nini has them', 'ahora mi Nini tiene', ''),
( '3o', 'of filling up the hours',      'de ocupar las horas', ''),
( '4g', 'without even noticing',        'sin darme ni cuenta', ''),
( '4i', 'it takes me ages',     'me demoro', ''),
( '3a', 'were no longer looking for me',        'ya no me buscaban', ''),
( '3n', 'from depression',      'de la depresión', ''),
( '3l', 'she know they contain',        'se que contienen', ''),
( '3d', 'when my life went off the rails',      'cuando se me torció el destino', ''),
( '4m', 'several pages later',  'unas páginas mas adelante', ''),
( '4k', 'even if you go for years',     'si uno pase de años', ''),
( '4f', 'ItZZZs complicated',   'me resulta complicado', ''),
( '4m', 'and thereZZZs no way to fit it in',    'y no hay modo de intercalarla', ''),
( '3n', 'saved her',    'la salvó', ''),
( '3o', 'time stretches out here',      'aquí el tiempo se estira', ''),
( '4e', 'on the map',   'en el mapa', ''),
( '3b', 'no amount of precaution could ever be enough', 'toda medida de precaución es poca', ''),
( '3n', 'because one of them',  'porque uno de ellos', ''),
( '3k', 'to untie the knots',   'para desatar los nudos', ''),
( '3d', 'until I was fifteen',  'hasta los quince', ''),
( '4l', 'and I thought',        'y pensé', ''),
( '3a', 'until we could be sure that',  'hasta que tuviéramos la certeza de que', ''),
( '3k', 'because they contain the keys',        'porque contienen los claves', ''),
( '4n', 'my memory goes in circles',    'mi memoria se mueve en circulos', ''),
( '4n', 'spirals and somersaults',      'espirales y saltos de trapecista', ''),
( '4o', 'my name is Maya Vidal',        'soy Maya Vidal', ''),
( '4p', 'IZZZm nineteen years old',     'diecinueve años', ''),
( '4p', 'female, single',       'sexo femenino, soltera', ''),
( '4p', 'without a boyfriend',  'sin un enamorado', ''),
( '4p', 'due to a lack of opportunities',       'por falta de oportunidades', ''),
( '4q', 'rather than by choice',        'y no por quisquillosa', ''),
( '4r', 'born in Berkeley',     'nacida en Berkeley', ''),
( '4r', 'American passport',    'pasaporte estadounidense', ''),
( '4r', 'temporarily taking refuge',    'temporalmente refugiada', ''),
( '4r', 'on an island', 'en una isla', ''),
( '4r', 'at the bottom of the world',   'al sur del mundo', ''),
( '4s', 'they named me Maya',   'me pusieron Maya', ''),
( '4s', 'because my Nini',      'porque a mi Nini', ''),
( '4s', 'has a soft spot for India',    'le atrae la India', ''),
( '4s', 'and my parents hadnZZZt come up with', 'y a mis padres no se les ocurrió', ''),
( '4s', 'any other name',       'otro nombre', ''),
( '4s', 'even though',  'aunque', ''),
( '4s', 'theyZZZd had nine months',     'tuvieron nueve meses', ''),
( '4s', 'to think about it',    'para pensarlo', ''),
( '4t', 'in Hindi',     'en hindi', ''),
( '4t', 'maya means charm, illusion, dream',    'maya significa hechizo, ilusión, sueño', ''),
( '4t', 'nothing at all to do', 'nada que ver', ''),
( '4t', 'with my personality',  'con mi carácter', ''),
( '4u', 'Attila would suit me better',  'Atila me calzaría mejor', ''),
( '4u', 'because wherever I step',      'porque donde pongo el pie', ''),
( '4u', 'no pasture will ever grow again',      'no sale más pasto', ''),
( '4v', 'my story begins in Chile',     'mi historia comienza en Chile', ''),
( '4v', 'with my grandmother',  'con mi abuela', ''),
( '4v', 'a long time before I was born',        'mucho antes de que yo naciera', ''),
( '4v', 'because if she hadnZZZt emigrated',    'porque si ella no hubiera emigrado', ''),
( '4v', 'sheZZZd never have fallen in love',    'no se habría enamorado', ''),
( '4v', 'with my Popo', 'de mi Popo', ''),
( '4v', 'or moved to California',       'ne se habría instalado en California', ''),
( '4v', 'my father would never have met my mother',     'mi padre no habría conocido a mi madre', ''),
( '4v', 'and I wouldnZZZt be me',       'y yo no sería yo', ''),
( '4v', 'but rather a very different Chilean girl',     'sino una joven chilena muy diferente', '');
UPDATE yacback SET en = replace(en, 'ZZZ', "'");
